#!/usr/bin/env python3
"""
Germany News Agent — Interactive Setup Wizard 🐅

Walks you through configuring the agent for your region, generates config.json,
TOOLS.md snippets, and OpenClaw cron job. Run once after cloning.

Usage:
    python setup.py
"""

import json, os, sys, re, shutil

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

def ask(question, default=None, required=False):
    """Ask a question and return the answer."""
    hint = f" [{default}]" if default else ""
    while True:
        answer = input(f"  {question}{hint}: ").strip()
        if not answer:
            if default:
                return default
            if required:
                print("  ⚠️  This is required. Please enter a value.")
                continue
            return ""
        return answer

def ask_list(question, hint_text="comma-separated"):
    """Ask for a comma-separated list and return as cleaned list."""
    raw = ask(f"{question} ({hint_text})")
    if not raw:
        return []
    items = [x.strip() for x in raw.split(",") if x.strip()]
    return items

def main():
    print()
    print("╔══════════════════════════════════════════════════╗")
    print("║    Germany News Agent — Setup Wizard 🐅         ║")
    print("╚══════════════════════════════════════════════════╝")
    print()
    print("Let's configure your agent for YOUR region.")
    print()
    
    # ── Step 1: Location ──
    print("── Step 1: Your Location ──────────────────────────")
    print("  These are the towns/cities you care about most.")
    print("  Articles mentioning these get Tier 1 (top billing).")
    print()
    
    tier1 = ask_list("Your local town(s) / city(ies)")
    if not tier1:
        print("  ⚠️  Setting defaults to 'Munich' example keywords.")
        print("     Edit config.json later to fix.")
        tier1 = ["munich", "muenchen"]
    
    tier2 = ask_list("Your wider region (e.g. cities in your area)")
    if not tier2:
        tier2 = ["bayern", "bavaria"]
    
    tier3 = ask_list("National keywords you care about (e.g. germany)")
    if not tier3:
        tier3 = ["deutschland", "germany", "berlin"]
    
    feed_boost = ask_list("Feeds to always boost (exact feed names from config)")
    
    # ── Step 2: OpenClaw integration (optional) ──
    print()
    print("── Step 2: OpenClaw Integration (optional) ────────")
    print("  Skip with Enter if not using OpenClaw.")
    print()
    
    oc_path = ask("OpenClaw workspace path", default=os.path.expanduser("~/.openclaw/workspace"))
    
    discord_channel = ask("Discord channel ID (or name) for delivery")
    
    schedule_day = ask("Schedule day (1=Mon, 2=Tue... or 'monday')", default="monday")
    
    # Normalize day name
    day_map = {
        "monday": "1", "tuesday": "2", "wednesday": "3", "thursday": "4",
        "friday": "5", "saturday": "6", "sunday": "0",
        "mon": "1", "tue": "2", "wed": "3", "thu": "4", "fri": "5", "sat": "6", "sun": "0",
    }
    cron_day = day_map.get(schedule_day.lower().strip(), schedule_day)
    
    schedule_time = ask("Time (CET, HH:MM format)", default="09:30")
    try:
        hour, minute = schedule_time.strip().split(":")
    except:
        hour, minute = "09", "30"
    
    # ── Step 3: Generate config ──
    print()
    print("── Step 3: Generating config.json ─────────────────")
    
    # Read existing feeds from current config as a template
    default_feeds = {
        "SZ FFB": "https://rss.sueddeutsche.de/fuerstenfeldbruck",
        "SZ Munchen": "https://rss.sueddeutsche.de/rss/Muenchen",
        "SZ Bayern": "https://rss.sueddeutsche.de/rss/Bayern",
        "Bild Munchen": "http://www.bild.de/rss-feeds/rss-16725492,feed=muenchen.bild.html",
        "FAZ": "https://www.faz.net/rss/aktuell",
        "Merkur FFB": "https://www.merkur.de/lokales/fuerstenfeldbruck/rssfeed.rdf",
        "Presseportal": "https://www.presseportal.de/blaulicht/rss"
    }
    
    config = {
        "_comment": "Germany News Agent — generated by setup.py. Edit freely.",
        "feeds": default_feeds,
        "keywords": {
            "tier1": tier1,
            "tier2": tier2,
            "tier3": tier3
        },
        "feed_boost": feed_boost,
        "compact_counts": {"local": 5, "bavaria": 5, "germany": 5},
        "detailed_per_source": 5
    }
    
    config_path = os.path.join(SCRIPT_DIR, "config.json")
    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2, ensure_ascii=False)
    
    print(f"  ✅ Written to {config_path}")
    print()
    
    # ── Step 4: Show summary ──
    print("── Summary ────────────────────────────────────────")
    print(f"  Local (Tier 1):   {', '.join(tier1)}")
    print(f"  Region (Tier 2):  {', '.join(tier2)}")
    print(f"  National (Tier3): {', '.join(tier3)}")
    print(f"  Boosted feeds:    {', '.join(feed_boost) if feed_boost else '(none)'}")
    print()
    
    # ── Step 5: Output tools / cron snippets ──
    print("── OpenClaw: TOOLS.md Triggers ────────────────────")
    print("  Copy-paste this into your TOOLS.md or AGENTS.md:")
    print()
    tools_snippet = f"""## Germany News Agent

When Asif says these in ANY channel, run the Python script — do NOT answer conversationally:

- `germany news` → compact mode: `cd {SCRIPT_DIR} ; $env:PYTHONIOENCODING='utf-8' ; python germany_news.py`
- `full news` → detailed mode: `cd {SCRIPT_DIR} ; $env:PYTHONIOENCODING='utf-8' ; python germany_news.py --detailed`

These are **hard triggers** — execute the script, capture stdout, output the result. No chit-chat about what "full news" means.

## @Tipu Summary Command

When Asif tags me with a number in any channel:
- `@Tipu <number> [short|detailed|bullet]` → scrape + BART summarize that article
- Look up the article number in `{os.path.join(SCRIPT_DIR, 'last_news_articles.json')}` first
- If no mapping file exists, reply: "No recent news found — run `germany news` or `full news` first"
- If number is out of range, reply: "Article #X not found — valid numbers: 1-N"
- Run summary: `cd {SCRIPT_DIR} ; $env:PYTHONIOENCODING='utf-8' ; python summarize.py "<url>" [short|detailed|bullet]`
- Default qualifier is `detailed` if not specified"""
    
    print(tools_snippet)
    print()
    
    if oc_path and os.path.isdir(os.path.dirname(oc_path)):
        tools_path = os.path.join(oc_path, "TOOLS.md")
        try:
            with open(tools_path, "a", encoding="utf-8") as f:
                f.write("\n\n" + tools_snippet + "\n")
            print(f"  ✅ Also appended to {tools_path}")
        except:
            print(f"  ⚠️  Could not write to {tools_path} — paste manually.")
    
    print()
    print("── OpenClaw: Cron Job ─────────────────────────────")
    print("  Create a cron job in OpenClaw like this:")
    print()
    
    cron_json = json.dumps({
        "name": "germany-news-weekly",
        "schedule": {
            "kind": "cron",
            "expr": f"{minute} {hour} * * {cron_day}",
            "tz": "Europe/Berlin"
        },
        "sessionTarget": "isolated",
        "payload": {
            "kind": "agentTurn",
            "message": f"Run the script and output the result: cd {SCRIPT_DIR} && python germany_news.py"
        },
        "delivery": {
            "mode": "announce",
            "channel": "discord",
            "to": f"channel:{discord_channel}" if discord_channel else "channel:YOUR_CHANNEL_ID"
        }
    }, indent=2)
    print(cron_json)
    print()
    
    # ── Step 6: Verify ──
    print("── Step 6: Verification ───────────────────────────")
    print("  Running basic sanity check...")
    
    errors = []
    
    # Check Python
    if sys.version_info < (3, 9):
        errors.append("Requires Python 3.9+")
    
    # Check deps installed
    missing_deps = []
    for pkg in ["argostranslate", "trafilatura", "transformers"]:
        try:
            __import__(pkg.replace("-", "_"))
        except ImportError:
            missing_deps.append(pkg)
    
    if missing_deps:
        print(f"  ⚠️  Missing packages: {', '.join(missing_deps)}")
        print(f"     Run: pip install -r requirements.txt")
    else:
        print("  ✅ All Python packages installed")
    
    # Check config
    try:
        with open(config_path, encoding="utf-8") as f:
            cfg = json.load(f)
        assert "keywords" in cfg
        assert "feeds" in cfg
        assert len(cfg["feeds"]) > 0
        print(f"  ✅ Config valid ({len(cfg['feeds'])} feeds)")
    except Exception as e:
        errors.append(f"Config error: {e}")
    
    if errors:
        print()
        for e in errors:
            print(f"  ❌ {e}")
    else:
        print("  ✅ All checks passed!")
    
    print()
    print("───────────────────────────────────────────────────")
    print("  ✅ Setup complete! Next steps:")
    print("  1. Review config.json and tweak feeds/keywords")
    print("  2. Paste the TOOLS.md snippet into your agent config")
    print("  3. Create the cron job in OpenClaw")
    print("  4. Run: python germany_news.py")
    print()
    print("  🐅 Happy news hunting!")
    print()

if __name__ == "__main__":
    main()
